### ISSUE TITLE
Add support for enumerating iteration elements in for-loop

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#781] opened 2021-04-08 14:42 UTC
### Issue To Be Solved

It would be convenient to have the ability to iterate over an array and get the index of the element currently being accessed instead of having to track it explicitly

### Suggest A Solution

```
let array: [Int] = [6,3,4,6]

for index, element in array {
    log(index)
    log(element)
}

// Would output "0,6, 1,3, 2,4, 3,6"
```

**Comment by turbolent** [comment] 2022-01-28 00:02
Duplicate of #402, was implemented in #1216

**Closed by turbolent** 2022-01-28 00:02 UTC
Labels: Feature, Feedback
