### ISSUE TITLE
remove and re-deploy may implement the ability like "update" but without some restrictions.

### ISSUE THREAD

**Issue by xiyu1984** [onflow/cadence#1569] opened 2022-04-12 07:13 UTC
### Instructions

I found that `remove` and re-`deploy` a contract may implement the ability like contract "update" but without some restrictions.

### Problem

I made a test for the lifespan of a resource on Flow. When I was testing it, I found some interesting things.

As we know from the [doc](https://docs.onflow.org/cadence/language/contract-updatability/#gatsby-focus-wrapper), contracts update has many restrictions.

We found a more flexible way to do the "update", that is, by `remove` the contract and re-`deploy` it.

The resource created by the older contract is just the same(with the same `uuid` and can be visited as before) after the contract has been removed, re-written with some features breaking the restrictions of `update`, and re-deployed.

### Steps to Reproduce

The details of this issue can be seen [here](https://github.com/xiyu1984/CadenceCook/tree/main/project/resourceLifespan)

**Comment by j1010001** [comment] 2022-10-19 18:10
duplicate of https://github.com/onflow/cadence/issues/1670, closing

**Closed by j1010001** 2022-10-19 18:10 UTC
Labels: Bug, Feedback
