### ISSUE TITLE
Add report for staged contracts in the migration

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3219] opened 2024-04-04 18:13 UTC
We need some easy way to share with the developers result of their staged contract upgrade when we run C1.0 migration.

**Comment by turbolent** [comment] 2024-04-04 19:52
Is this potentially a duplicate of #3116?

**Comment by SupunS** [comment] 2024-04-04 23:46
> Is this potentially a duplicate of https://github.com/onflow/cadence/issues/3116?

Potentially yeah. I think we could repurpose #3116 to also include the additional work needed to publish the results somewhere so that developers can access it (and make it more presentable), and also for keeping that published results up to date.

Where as this issue can only focus on generating the raw report.

**Comment by SupunS** [comment] 2024-04-10 15:25
Added in https://github.com/onflow/flow-go/pull/5630

**Closed by SupunS** 2024-04-10 15:25 UTC
