### ISSUE TITLE
Unexpected changes in an account's storage capacity 

### ISSUE THREAD

**Issue by chandanworkacct** [onflow/cadence#1367] opened 2022-01-18 17:14 UTC
### Problem

Querying the storage capacity of an account returns different values even though there is no change in the number of FLOW tokens held by the account.

Here is an example transaction.
https://flow-view-source.com/testnet/tx/5f34f968421e7777cfa71583f5f761c903914500992f6881507d1e5776ed1ef1

Please note that a similar transaction doesn't display the issue.
https://flow-view-source.com/testnet/tx/6669920efbc135c6bb8d2871a1b7a27d42d0dc3c1914b86baba45155e4a28f38

### Steps to Reproduce

Execute the transaction mentioned in this link:
https://flow-view-source.com/testnet/tx/5f34f968421e7777cfa71583f5f761c903914500992f6881507d1e5776ed1ef1

**Comment by turbolent** [comment] 2022-02-11 19:19
Research so far: Not a Cadence issue, likely a FVM issue. Robert will keep investigating, will ask for help from Janez when possible

**Comment by robert-e-davidson3** [comment] 2022-02-16 03:19
The links are broken. Here are some that work:
- https://testnet.flowscan.org/transaction/5f34f968421e7777cfa71583f5f761c903914500992f6881507d1e5776ed1ef1/script
- https://testnet.flowscan.org/transaction/6669920efbc135c6bb8d2871a1b7a27d42d0dc3c1914b86baba45155e4a28f38/script

**Comment by turbolent** [comment] 2022-02-25 19:16
@janezpodhostnik Could you or someone else from EN/FVM help Robert with reproducing the problem? Maybe we can replay the particular transaction in question using the remote debugger?

**Comment by janezpodhostnik** [comment] 2022-02-25 19:39
Perhaps it has something to do with this: https://github.com/onflow/cadence/blob/929eabba05264ff5ab8e4174ef97823f3b6afaca/runtime/runtime.go#L1841 and the lack of this commit when asking for storage capacity...

@robert-e-davidson3 Lets get together next week and try using the remote debugger.

**Comment by robert-e-davidson3** [comment] 2022-03-09 01:37
There's a more basic bug here: `signer.storageCapacity` does not update when the flow token balance changes:

```
				var cap0: UInt64 = signer.storageCapacity
				receiverRef.deposit(from: <- vaultRef.withdraw(amount: 1.0))
				var cap1: UInt64 = signer.storageCapacity
				panic("cap0=".concat(cap0.toString()).concat("; cap1=").concat(cap1.toString()).concat("; diff=").concat((cap0 - cap1).toString()))
```
`panic: cap0=1192313051173589; cap1=1192313051173589; diff=0`

This bug report is so weird because it _does_ update when `signer.storageUsed` is called:
```
				var cap0: UInt64 = signer.storageCapacity
				receiverRef.deposit(from: <- vaultRef.withdraw(amount: 1.0))

				signer.storageUsed

				var cap1: UInt64 = signer.storageCapacity
				panic("cap0=".concat(cap0.toString()).concat("; cap1=").concat(cap1.toString()).concat("; diff=").concat((cap0 - cap1).toString()))
```
`panic: cap0=1192313051173589; cap1=1192312951173589; diff=100000000`

(I tested using remote debugging against testnet.)

**Comment by turbolent** [comment] 2022-03-09 04:08
Great analysis @robert-e-davidson3! 

I think we had not considered that the `storageCapacity` may also change during program execution, if the account received FLOW. Storage changes are not committed until the end of program execution. Because of that, `storageUsed` already commits changes when it is accessed. The solution here might be to also commit when `storageCapacity` is accessed.

**Closed** 2022-03-23 23:21 UTC
Labels: Bug, Feedback
