### ISSUE TITLE
Inherited structure typing no longer works on newest emulator and testnet

### ISSUE THREAD

**Issue by NtTestAlert** [onflow/cadence#2785] opened 2023-09-14 17:12 UTC
### Current Behavior

https://testnet.flowdiver.io/tx/7f2395f1e696499f6cfc009f4e2e3db9bf0d56498e44f62c706f21d7d07c713d?tab=script

The contract correctly deploys, but using a function that uses a contract struct causes internal cadence CCF errors

```

[Error Code: 1101] error caused by: 1 error occurred:
	* transaction execute failed: [Error Code: 1101] cadence runtime error: Execution failed:
  --> 7f2395f1e696499f6cfc009f4e2e3db9bf0d56498e44f62c706f21d7d07c713d:29:23
   |
29 |             let pack <-self.operator.mint(distId: distId, metadata: metadatas[i], collectionMetadata: nil, additionalInfo: nil, commitHash: commitHash, issuer: self.issuer, nftCount: nftCounts[i], lockTime: lockTimes[i])
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


error: internal error: CCF type ID not found for type A.723a1b50e1d67e8e.PackNFT.Metadata
goroutine 12648648964 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/onflow/cadence/runtime/errors.NewUnexpectedErrorFromCause(...)
	/go/pkg/mod/github.com/onflow/cadence@v0.39.14/runtime/errors/errors.go:152
github.com/onflow/cadence/encoding/ccf.(*Encoder).encodeInlineType(0x29c3840?, {0x29c3840?, 0xd8cc1e5620?}, 0xd8cc1e5620?)
	/go/pkg/mod/github.com/onflow/cadence@v0.39.14/encoding/ccf/encode_type.go:68 +0x38d
````

### Expected Behavior

An interface defines an NFT, and common event definitions that include structs.
A contract then has to conform to those definitions while extending the interface's structs

This used to work properly, but was hard to implement.

Works fine on emulator version gcr.io/flow-container-registry/emulator:0.38.1

### Steps To Reproduce

Truncated code:

```
pub contract interface IPackNFT{
  pub event Mint(id: UInt64, edition: UInt64, commitHash: String, distId: UInt64, metadata: Metadata)
  pub struct Metadata { }
}
```

```
pub contract PackNFT: NonFungibleToken, IPackNFT {
  pub event Mint(id: UInt64, edition: UInt64, commitHash: String, distId: UInt64, metadata: IPackNFT.Metadata)
    

    pub struct Metadata {
        pub let name: String
        pub let description: String
  [...]
  }
  pub resource PackNFTOperator {
    pub fun mint(distId: UInt64, metadata: IPackNFT.Metadata){ ... }
}
```

transaction

```

transaction(distId: UInt64, metadatas: [PackNFT.Metadata], recipient: Address) {
    let operator: &PackNFT.PackNFTOperator
    let issuer: Address

    prepare(signer: AuthAccount) {
        self.issuer = signer.address
        self.operator = signer.borrow<&PackNFT.PackNFTOperator>(from: PackNFT.OperatorStoragePath)!
    }


    execute {
        let recipient = getAccount(recipient)
        let recipientRef = recipient
            .getCapability<&PackNFT.Collection{NonFungibleToken.CollectionPublic}>(PackNFT.CollectionPublicPath)
            .borrow()
            ?? panic("Could not get recipient reference to the PackNFT Collection")

        for i, commitHash in commitHashes {
            let pack <-self.operator.mint(distId: distId, metadata: metadatas[i])
            recipientRef.deposit(token: <-pack)
        }
    }
}
```

### Environment

```markdown
"cadence-tag": "v0.39.14",
- Network: Testnet47
```

**Comment by turbolent** [comment] 2023-09-14 17:39
So from what I see so far, it looks like it's an omission in the type checker: the use of the nested type requirement in the event declaration should be rejected, but isn't.

Nested type requirements should be rejected, just like interfaces are rejected, because the event parameter check determines if event emission is supported, and that is impossible for an abstract type, as it may have different concrete values at run-time.

Assuming this used to work by accident before event encoding was switched from JSON to CCF, this is a regression.

Options for next steps:
- We do not accept the regression and restore the previous functionality, accepting that it should have not worked previously, but is being actively used in Mainnet contracts. This probably means we need to improve the CCF encoding, but I don't quite know yet what that would entail.
- We accept the regression / the accidental breaking change, and fix the type checker to reject uses of nested type requirements in event declarations. This is simple to fix and would result in a better error message. Developers would need to update their contracts if they are running into this issue.

Given that nested type requirements are already removed in Stable Cadence, so developers will need to update their contracts eventually anyways if they currently use nested type requirements, I'd suggest to go with the latter option.

**Comment by NtTestAlert** [comment] 2023-09-14 18:18
Is there an alternative to defining the events - which use structures - in a way that enforces conformity for implementing contracts? 
Currently and/or in Stable Cadence?

**Comment by turbolent** [comment] 2023-09-26 19:35
We discussed this in the team. Ideally, we would like to fix the accidental breaking change. That would require extending CCF codec to support this use-case, just as it was supported by the JSON-CDC codec (unintentionally).

However, the team currently does not have the capacity to take on that work. In addition, the time when there is bandwidth available is likely going to coincide with the release of Stable Cadence / Cadence 1.0, where contracts using this "feature" will have to get changed anyways.

We therefore decided to focus on at least improving the user experience, for the new behaviour, by reporting a proper error message when type checking invalid contracts.

**Comment by turbolent** [comment] 2023-09-26 20:14
Opened #2816 to track the improvement.

**Comment by SupunS** [comment] 2024-04-02 18:49
Closing this as the underlying improvement is tracked via https://github.com/onflow/cadence/issues/2816

**Closed by SupunS** 2024-04-02 18:49 UTC
Labels: Bug, Feedback
