### ISSUE TITLE
Sending a transaction that emits event with argument of type array causes flow cli to crash

### ISSUE THREAD

**Issue by sukantoraymond** [onflow/cadence#1672] opened 2022-05-26 15:44 UTC
### Issue To Be Solved
We found that sending transactions that emits events that contain array as arguments causes flow cli to crash. We have replicated the issue on flow cli in emulator network and the logs obtained from sentry is attached. To replicate, deploy the code below

```
pub contract HelloWorld {

    pub event FooEvent(x: [String]?)
    pub let greeting: String
    pub var arrayEvent: [String]
    init() {
        self.greeting = "Hello, World!"
        self.arrayEvent = ["Event"]
    }

    pub fun hello(): String {
        emit FooEvent(x: self.arrayEvent)
        return self.greeting
    }
}
```
and send the transaction using the code below.  

```
import HelloWorld from 0xf8d6e0586b0a20c7

transaction {
	prepare(acct: AuthAccount) {}
	execute {
	  	log(HelloWorld.hello())
	}
}

```

### Suggested Solution
Seems that JSON-CDC is not encoding element type in array (e.g. [String]? ends up as []?)

<img width="940" alt="Screen Shot 2022-05-25 at 2 53 13 PM" src="https://user-images.githubusercontent.com/23159488/170523843-acb01a6a-b229-40e2-a6e2-8a5ab37d104a.png">

**Comment by turbolent** [comment] 2022-05-26 16:33
This is https://github.com/onflow/flow-cli/issues/486

**Comment by sukantoraymond** [comment] 2022-05-26 16:35
@turbolent Yup, we replicated this issue, and think that this issue exists in cadence

**Comment by SupunS** [comment] 2022-05-27 20:59
So the issue is that, the type info is never added during the conversion from cadence internal values to the external values. This problem may potentially be there for some other types of values as well (e.g: dictionary).

There's an already an issue for adding this: https://github.com/onflow/cadence/issues/1378. However, this would be a breaking change as it needs to change the JSON-cadence data format as well.

A temporary workaround would be to handle the panics on `type.ID()` conversion, similar to the [nil check here](https://github.com/onflow/flow-cli/blob/ea543c212734cdb21c340c940a589f677c0d7b55/internal/events/events.go#L135). That existing check only captures one level, but doesn't catch the nested types.

**Comment by bluesign** [comment] 2022-05-30 16:48
@SupunS maybe some nil check here:

https://github.com/onflow/cadence/blob/1a7687f0fce253b28e931db1fa16b822fc2071d4/types.go#L71

**Comment by j1010001** [comment] 2022-06-03 18:26
low priority, fixed in CLI, we will revisit this as part of the Cadence Value Encoding EPIC

**Comment by turbolent** [comment] 2022-06-24 15:30
Quickly added this information, didn't realize Robert got assigned, sorry

**Closed** 2022-06-27 17:48 UTC
Labels: Bug, Breaking Change, Feedback, P-Low
