### ISSUE TITLE
Should publish @onflow/cadence-parser in sync with Cadence version

### ISSUE THREAD

**Issue by LemonNekoGH** [onflow/cadence#2392] opened 2023-03-18 03:52 UTC
As of today (March 18th, 2023), we can only download version `0.26.0` of `@onflow/cadence-parser`, it's not the latest version of Cadence, it should be `0.36.0`.
Although we can build and publish it by self, but I don't think it's a good practice.

**Comment by j1010001** [comment] 2023-03-23 21:17
Possible solution is to automatically build the npm package with GH automation, similar to what FCL does @JeffreyDoyle might help.

**Comment by turbolent** [comment] 2024-09-26 22:05
Duplicate of #2003

**Closed by turbolent** 2024-09-26 22:05 UTC
Labels: P-Low
