### ISSUE TITLE
static type and runtime type doesn't match for publicKey in flow events

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#2525] opened 2023-06-04 02:43 UTC
### Current Behavior

Currently, `publicKey` field's static type and runtime type are different in the latest version of `AccountKeyAdded` and `AccountKeyRemoved` events.

For example, `flow.AccountKeyAdded`:
- event type has `publicKey` field type `[UInt8]` (static type).
- event value has `publicKey` field as `Struct` (runtime type).

### Proposed Solution

`publicKey` should have matching static type and runtime type.

**Comment by turbolent** [comment] 2023-06-04 20:55
This is a duplicate of #1796. 

In Stable Cadence, the deprecated key APIs got removed, so `PublicKey` should be the type of the event field.

**Comment by fxamacker** [comment] 2023-06-04 21:16
> In Stable Cadence, the deprecated key APIs got removed, so PublicKey should be the type of the event field.

@turbolent I see, thanks!

This issue and PR #2528 were opened because this is a blocker for CCF event encoding PR https://github.com/onflow/flow-go/pull/4417.   And the PR #2528 supports both APIs.

Should we support both APIs until Stable Cadence is released?

**Closed** 2023-06-05 16:29 UTC
Labels: Bug, Feedback
