### ISSUE TITLE
Accessing resource reference causes "missing value for member" error if resource has been moved

### ISSUE THREAD

**Issue by mikeylemmon** [onflow/cadence#1539] opened 2022-03-27 04:25 UTC
### Problem

I recently upgraded my project from cadence v0.18.1 to v0.23.0 (flow-cli v0.28.3 -> v0.31.2) and started getting `missing value for member` errors in contracts that didn't have any problems before. I traced the issue to the use of references to resources where the reference was created before the resource was transferred to a different account — after transfer, the reference is non-nil, but any attempt to access properties of the reference result in the error "missing value for member <property-name>". Previously, the references remained valid after transfer and properties could be accessed without error.

### Steps to Reproduce

I have reproduced the issue in the Flow Playground by slightly modifying the "Cadence Marketplace Tutorial" playground:

#### Changes:
* Add `getReference` method to Collection resource in ExampleNFT contract:
    ```
        pub fun getReference(id: UInt64): &NFT {
            return &self.ownedNFTs[id] as &NFT
        }
    ```

* Use the new `getReference` method in ExampleMarketplace purchase method to obtain a reference to the NFT that is being purchased; access the `id` property of the reference after the NFT has been transfered to the buyer:
    ```
      // pub fun purchase(...) {
            // ...

            let nftRef = self.ownerCollection.borrow()!.getReference(id: tokenID)
            log("NFT Reference before transfer:")
            log(nftRef)

            // deposit the NFT into the buyers collection
            receiverReference.deposit(token: <- self.ownerCollection.borrow()!.withdraw(withdrawID: tokenID))

            log("NFT Reference after transfer:")
            log(nftRef)
            log(nftRef.id)
    ```

#### Steps to reproduce:
https://play.onflow.org/ebde5a12-6292-40d5-86a1-42c9eca8b611
1. Deploy contracts for 0x01, 0x02, 0x03 (ExampleToken, ExampleNFT, ExampleMarketplace)
2. Run transactions 1 through 5. Transaction 5 ("Purchase NFT") will fail with the `missing value for member` error

**Comment by turbolent** [comment] 2022-03-28 22:06
Thank you for reporting this @mikeylemmon! 

This was indeed a bug and should have been fixed by #1344. This fix was released a while ago. 
The Playground is on an older version of Cadence, v0.20.0.

I see that the code is failing in the Playground. Were you also able to reproduce this in the latest emulator? 

I took the code from the Playground as-is and created a test case, but it it succeeds in the releases since #1344 was merged (including the latest Cadence release v0.23.2 and the master branch)

**Comment by turbolent** [comment] 2022-03-28 22:08
Thank you for the report @mikeylemmon, including the great reproduction! 

I'm able to reproduce the bug locally and am investigating.

**Comment by j1010001** [comment] 2022-04-22 18:09
Still needs a fix

**Comment by turbolent** [comment] 2022-04-25 23:35
I had a pushed a reproducing test case in 693eb41678e6716154bc2e2ffcb58a0b02bc1d75 back in March.

The problem is related to #1320: When a reference to a resource-kinded object (resource on its own, array, dictionary, optional) is created, and the object is transfered to another address in storage (e.g. from the stack to an account), then all references must be updated to point to the transfered object.

This was fixed for resources, arrays, and dictionaries in #1344, by tracking all created references to resource-kinded objects by their storage ID. 

However, unlike resources (`CompositeValue`), arrays (`ArrayValue`), and dictionaries (`DictionaryValue`), optionals (`SomeValue`) are not stored in separate slabs, so do not have their own storage ID, they may be inlined when stored.
This makes it impossible to track references to optionals by storage ID like for the other resource-kinded objects.

However, @dsainati1 pointed out that with #1303 changing the semantics for taking a reference to an optional, it should not be possible to run into this edge-case anymore.

@dsainati1 to double check

**Comment by dsainati1** [comment] 2022-05-02 17:26
I took a look into this but was unable to determine whether the bug reported here is still an issue after https://github.com/onflow/cadence/pull/1303 because while testing this on the secure cadence branch I ran into a separate issue.

I have added a repro for this issue here: https://github.com/onflow/cadence/commit/8f05eba8ea0a14b7041810de03171ecda9cec2f5, but the important point is that the last two transactions in the original repro above do not need to run in order to see this issue; the issue occurs before we even take a reference to the resource or an optional. Specifically the error occurs on this line: https://github.com/onflow/cadence/commit/8f05eba8ea0a14b7041810de03171ecda9cec2f5#diff-837f51768ca6bde6f2fdd2f1216cbd41ae1846b0944998f2241d558ee155ce77R4335, when the newly minted NFT is saved to the account. It seems like borrowing the resource from the capability somehow is failing. 

The specific error is 
```
error: resource is invalidated and cannot be used anymore
--> 0000000000000001.ExampleToken:0:0
```

**Comment by bluesign** [comment] 2022-05-02 17:56
after resource has moved how can reference still be valid? am I missing something here ?

**Comment by turbolent** [comment] 2022-05-09 22:12
@bluesign The current behaviour is that references to resources stay valid no matter where the resource is located, e.g. if a resource is created, a reference to it is created, and the resource is moved to storage, the reference is still valid.

One could argue that references could become invalid once the resource is moved (e.g. from the "stack" to an account, or from one account to the "stack" or into another account), and we have thought about implicated, but that would be a breaking change, so for now we want to ideally keep the existing behaviour working.

**Closed** 2022-05-09 22:19 UTC
Labels: Bug, Feedback, P-Medium

**Comment by bluesign** [comment] 2022-05-10 14:37
@turbolent I would strongly suggest to change this in stable cadence. I don't have solid example now but I feel this is really dangerous.
