### ISSUE TITLE
Migrate empty storage maps in atree migration

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3409] opened 2024-06-11 15:41 UTC
Discord thread: https://discord.com/channels/613813861610684416/1248713111943254228/1250103727256240220

**Comment by fxamacker** [comment] 2024-06-14 02:55
Duplicate of #3408 and closed by flow-go PR https://github.com/onflow/flow-go/pull/6064

**Closed by fxamacker** 2024-06-14 02:55 UTC
Labels: Bug
