### ISSUE TITLE
Allow saving of types and capabilities into contracts/resources in Playground

### ISSUE THREAD

**Issue by MaxStalker** [onflow/cadence#373] opened 2020-09-14 15:09 UTC
### Instructions
NFT or contract could have a field specified on them, which gives a hint on type to cast the reference.

### Problem

Playground doesn't seem to support this at the moment.

### Steps to Reproduce

Here is Playground with test case:
https://play.onflow.org/603a8982-9198-4be7-9f55-0cc91ae29f6f

- Deploy `FungibleToken` contract from 0x01
- Try to deploy `CustomVault` contract from 0x02 - Playground will throw `GraphQL error: internal system error`

**Comment by turbolent** [comment] 2020-09-14 17:26
The error message is `cannot export value of type interpreter.TypeValue`, which comes from `cadence.exportValueWithInterpreter`.

This function is used by the Playground to show the account state, so the problem is only there – storage of type values is supported and should work in the emulator and on networks.

Related is #259, which added support for exporting links and references. I had listed the value type which still need to be added here https://github.com/onflow/cadence/issues/259#issuecomment-663223511, but it looks like the closing PR didn't add support for type values.

**Comment by turbolent** [comment] 2020-09-28 16:52
The cause for this is the missing support for exporting types and capabilities to JSON.

**Closed** 2020-09-28 19:23 UTC
Labels: Bug, Feedback
