### ISSUE TITLE
Dictionary literal does not honor sub-typing rules

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#521] opened 2021-01-11 06:59 UTC
### Problem
During the type-checking for dictionary literals, members (keys/values) who are sub-types of the defined dictionary, are considered as incompatible types.

The same member can be set using the 'access syntax', and the type-checking works correctly there.

### Steps to Reproduce

See the below example:

```rust
pub fun foo() {

    let myDictionary: {Int: AnyStruct} = {
           1: true,
           2: "hello"   // Type checking error: "mismatched types. expected `Bool`, got `String`"
       }

    myDictionary[2] = "hello"   // All good

}
```

### Acceptance Criteria

N/A

### Context

N/A

**Comment by turbolent** [comment] 2021-01-11 18:02
@SupunS Great point! 

The problem is here that the type inference to dictionary literals (also array literals) uses the type of the first key/value pair for the element type of the dictionary.

It would be great to extend this and use the join of all elements. There's already an issue to improve the type inference for array/dictionary literals and ternary expressions by finding the join type: #61.

Also, in this example the variable declaration has a type annotation, so we could also use this when it is available. Again, there's already an issue to add non-local type inference: #512. 

I'll close this issue as the two issues already cover the work needed to improve your example

**Closed by turbolent** 2021-01-11 18:02 UTC
Labels: Bug, Feedback
