### ISSUE TITLE
Missing temporary slab 

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1261] opened 2021-11-19 22:39 UTC
### Problem

> we encounter strange issue like bellow on testnet.
> https://testnet.flowscan.org/transaction/2da8630a336f15f20747bfdde6702e22bd8d9f72a1cb30a511ff39e834834492/script
> results in “[Error Code: 1101] cadence runtime error Execution failed: error: slab {[0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 48]} not found”.
>
> but, another transaction that executed by another address on testnet is working fine. (contract and script are same)
https://testnet.flowscan.org/transaction/faeabbb5732cf273c5317dcf47e86eeb3ea845e5ea1f0bca98c1fd3db7e6033b/script
>
> we have two accounts as signer.
> ng : https://flow-view-source.com/testnet/account/0x434a1f199a7ae3ba
> ok : https://flow-view-source.com/testnet/account/0xb9047a906effe57b
>
> contracts:
> https://github.com/mediadotech/smart-contracts/blob/main/contracts/FanTopMarket.cdc
> https://github.com/mediadotech/smart-contracts/blob/main/contracts/FanTopPermission.cdc
>
> transaction script:
> https://github.com/mediadotech/smart-contracts/blob/b9aed65770c1bf12300a3ae4edd1134ce9c7f5ef/transactions/minter/batch_mint_token.cdc
>
> to mint NFT on our contract, we need to add item info. u can check the transaction to do that.
https://github.com/mediadotech/smart-contracts/blob/b9aed65770c1bf12300a3ae4edd1134ce9c7f5ef/transactions/operator/create_item.cdc 
>
> we deployed our contract to new address and executed transaction was success! we can't get reproduction.
https://testnet.flowscan.org/transaction/85b07f2afcc5bed1c0a3a66e7576a3a8beeda7d6bd4f93f5d1033478f217fc7e
>
> [contract address ]
> https://flow-view-source.com/testnet/account/0xb668e8c9726ef26b

### Steps to Reproduce

- Use remote debugger against failing Testnet transaction

### Notes

- Storage address is 0x0, i.e. the value is on the stack, or expected to be

**Comment by fxamacker** [comment] 2021-12-07 20:50
It seems data corruption was caused by old code (already fixed) at 

https://github.com/onflow/cadence/blob/1566e18e12919fc233a23da9f0aecfe7967889b6/runtime/interpreter/value.go#L8345-L8360

Because `interpretr.TransferValue` should also be called for  `keyValue`.

This would explain the temp slab for key as composite type not being transferred to the permanent address.

In addition to this code already being fixed, the new migration has a Slab Health Check option which would detect this problem.

**Comment by turbolent** [comment] 2021-12-07 21:02
Additional context: Commit 1d52d1daa51d74a618ff0f6ea48837bf27044701 fixed the issue

**Comment by SupunS** [comment] 2021-12-13 20:19
I think we can close this issue? Or any further actions needed?

**Comment by fxamacker** [comment] 2021-12-16 00:56
> I think we can close this issue? Or any further actions needed?

I think this can be closed.  The bug never got deployed to mainnet.  And I don't think the limited amount of corrupted testnet data can be recovered.

**Comment by turbolent** [comment] 2021-12-16 22:27
Thank you again for investigating! We haven't gotten any further reports, and our own investigation confirmed the bug is resolved, so we can close this issue now

**Closed** 2021-12-16 22:28 UTC
Labels: Bug
